apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    name: bad-app-of-apps
  name: bad-app-of-apps
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: false
    path: bad-apps
    repoURL: https://github.com/opsmx-cnoe/naveen
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      backoff:
