apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bad-app
  template:
    metadata:
      labels:
        app: bad-app
    spec:
      containers:
        - name: bad-container
          image: nonexistentrepo/nonexistimage:latest 
          ports:
            - containerPort: eighty 
          env:
            - name: ENV_VAR_WITHOUT_VALUE  
