apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: missing-rs-pull-policy-svc-helm-chart-app 
  namespace: argocd
spec:
  destination:
    namespace: missing-rs-pull-policy-svc-helm-chart-app
    server: https://dev-vcluster.opencd.opsmx.org:443
  source:
    repoURL: https://github.com/opsmx-cnoe/naveen 
    path: bad-apps/bad-manifest/bad-helm-charts/missing-rs-svc-pull-helm-charts 
    targetRevision: main 
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
