apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: missing-pull-policy-helm-chart-app 
  namespace: argocd
spec:
  destination:
    namespace: missing-pull-policy-helm-chart-app 
    server: https://dev-vcluster.opencd.opsmx.org:443 
  source:
    repoURL: https://github.com/opsmx-cnoe/naveen 
    path: bad-apps/bad-manifest/bad-helm-charts/missing-pull-policy
    targetRevision: main 
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
