apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: two-helm-src-missing-rs-pull-policy 
  namespace: argocd
spec:
  destination:
    namespace: two-helm-src-missing-rs-pull-policy 
    server: 'https://target-vcluster.gartner.opsmx.net:443'
  sources:
    - repoURL:  https://github.com/opsmx-cnoe/naveen
      path: bad-apps/bad-manifest/bad-helm-charts/missing-rs-svc-pull-helm-charts 
      targetRevision: main 
      helm:
        valueFiles:
          - values.yaml
    - repoURL: https://github.com/opsmx-cnoe/naveen 
      path: bad-apps/bad-manifest/bad-helm-charts/missing-rs-svc-pull-helm-charts 
      targetRevision: main 
      helm:
        valueFiles:
          - values.yaml
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
